// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC56-UWfpzG9LPDg5WO-vaFzjgXIIlSYeY',
    appId: '1:169893296761:web:5b19466e57b0aa631db2a8',
    messagingSenderId: '169893296761',
    projectId: 'evoria-a72c3',
    authDomain: 'evoria-a72c3.firebaseapp.com',
    storageBucket: 'evoria-a72c3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXS7LcD_YbpV2FMzFjHBlxFUU7zI4gWr0',
    appId: '1:169893296761:android:c776224e133186f01db2a8',
    messagingSenderId: '169893296761',
    projectId: 'evoria-a72c3',
    storageBucket: 'evoria-a72c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH1Jmsl9MdIhg9ZQVQAPDx8md_BuYUiyc',
    appId: '1:169893296761:ios:2646f38aad31eeb11db2a8',
    messagingSenderId: '169893296761',
    projectId: 'evoria-a72c3',
    storageBucket: 'evoria-a72c3.firebasestorage.app',
    iosBundleId: 'com.example.evoriaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH1Jmsl9MdIhg9ZQVQAPDx8md_BuYUiyc',
    appId: '1:169893296761:ios:2646f38aad31eeb11db2a8',
    messagingSenderId: '169893296761',
    projectId: 'evoria-a72c3',
    storageBucket: 'evoria-a72c3.firebasestorage.app',
    iosBundleId: 'com.example.evoriaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC56-UWfpzG9LPDg5WO-vaFzjgXIIlSYeY',
    appId: '1:169893296761:web:2b8628772bf1a85e1db2a8',
    messagingSenderId: '169893296761',
    projectId: 'evoria-a72c3',
    authDomain: 'evoria-a72c3.firebaseapp.com',
    storageBucket: 'evoria-a72c3.firebasestorage.app',
  );

}