import '../event.dart';
import '../user_profile.dart';
import '../vendor.dart';

class MockData {
  // Sample Events
  static List<Event> sampleEvents = [
    Event(
      id: '1',
      name: 'Summer Festival 2024',
      title: 'Summer Festival 2024',
      description: 'Join us for a weekend of music, art, and fun at the annual Summer Festival.',
      imageUrl: 'assets/summer_party.png',
      date: DateTime(2024, 6, 15),
      time: '10:00 AM - 10:00 PM',
      location: 'City Park',
      category: 'Festival',
      price: 25.0,
      attendees: ['2500'],
      tags: ['Music', 'Art', 'Food', 'Family-friendly'],
      vendors: ['3', '5', '7'],
      theme: 'Summer',
      enableRSVP: true,
      enableBudgetTracker: true,
      enableTodoChecklist: true,
      createdAt: DateTime(2024, 5, 1),
    ),
    
    Event(
      id: '2',
      name: 'Elegant Wedding Show',
      title: 'Elegant Wedding Show',
      description: 'Discover the latest wedding trends, meet vendors, and get inspired for your big day.',
      imageUrl: 'assets/wedding_show.png',
      date: DateTime(2024, 7, 21),
      time: '12:00 PM - 5:00 PM',
      location: 'Grand Hotel',
      category: 'Expo',
      price: 15.0,
      attendees: ['800'],
      tags: ['Wedding', 'Bridal', 'Fashion'],
      vendors: ['1', '2', '8'],
      theme: 'Wedding',
      enableRSVP: true,
      enableBudgetTracker: true,
      enableTodoChecklist: true,
      createdAt: DateTime(2024, 5, 2),
    ),
    
    Event(
      id: '3',
      name: 'Retro Game Night Extravaganza',
      title: 'Retro Game Night Extravaganza',
      description: 'Step back in time with classic arcade games, board games, and retro video games. Prizes, snacks, and nostalgic fun for all ages!',
      imageUrl: 'assets/retro.png',
      date: DateTime(2024, 7, 12),
      time: '6:00 PM - 11:00 PM',
      location: 'Gaming Lounge Downtown',
      category: 'Entertainment',
      price: 20.0,
      attendees: ['150'],
      tags: ['Gaming', 'Retro', 'Fun'],
      vendors: ['2', '8', '15'],
      theme: 'Retro',
      enableRSVP: true,
      enableBudgetTracker: false,
      enableTodoChecklist: true,
      createdAt: DateTime(2024, 5, 3),
    ),

    Event(
      id: '4',
      name: 'Glow-in-the-Dark Mini Golf Tournament',
      title: 'Glow-in-the-Dark Mini Golf Tournament',
      description: 'Experience mini golf like never before! Neon lights, glowing obstacles, and cosmic fun. Tournament prizes and glow party afterwards!',
      imageUrl: 'assets/golf.png',
      date: DateTime(2024, 8, 18),
      time: '7:00 PM - 10:30 PM',
      location: 'Cosmic Golf Adventure',
      category: 'Sports',
      price: 15.0,
      attendees: ['200'],
      tags: ['Mini Golf', 'Glow', 'Tournament'],
      vendors: ['4', '9', '12'],
      theme: 'Glow',
      enableRSVP: true,
      enableBudgetTracker: false,
      enableTodoChecklist: true,
      createdAt: DateTime(2024, 5, 4),
    ),

    Event(
      id: '5',
      name: 'Paint & Sip Comedy Night',
      title: 'Paint & Sip Comedy Night',
      description: 'Create masterpieces while laughing at hilarious stand-up comedy! All art supplies included plus unlimited drinks and snacks.',
      imageUrl: 'assets/comedy.png',
      date: DateTime(2024, 9, 7),
      time: '7:30 PM - 10:00 PM',
      location: 'Art Studio & Bar',
      category: 'Art',
      price: 35.0,
      attendees: ['80'],
      tags: ['Painting', 'Comedy', 'Drinks'],
      vendors: ['1', '6', '11'],
      theme: 'Art',
      enableRSVP: true,
      enableBudgetTracker: true,
      enableTodoChecklist: true,
      createdAt: DateTime(2024, 5, 5),
    ),

    Event(
      id: '6',
      name: 'Bubble Run Fun Challenge',
      title: 'Bubble Run Fun Challenge',
      description: 'Run through thousands of colorful bubbles in this 5K fun run! Not timed, just pure joy. Bubble machines, music, and celebration!',
      imageUrl: 'assets/bubble.png',
      date: DateTime(2024, 5, 25),
      time: '9:00 AM - 12:00 PM',
      location: 'Sunshine Park',
      category: 'Sports',
      price: 30.0,
      attendees: ['1000'],
      tags: ['Bubbles', 'Fun Run', 'Colorful'],
      vendors: ['3', '7', '13'],
      theme: 'Fun Run',
      enableRSVP: true,
      enableBudgetTracker: false,
      enableTodoChecklist: true,
      createdAt: DateTime(2024, 5, 6),
    ),
    
    Event(
      id: '7',
      name: 'Escape Room Championship',
      title: 'Escape Room Championship',
      description: 'Teams compete in multiple themed escape rooms! Zombie apocalypse, space station, haunted mansion, and more. Ultimate puzzle challenge!',
      imageUrl: 'assets/escape.png',
      date: DateTime(2024, 10, 31),
      time: '2:00 PM - 8:00 PM',
      location: 'Mystery Escape Complex',
      category: 'Entertainment',
      price: 40.0,
      attendees: ['120'],
      tags: ['Escape Room', 'Puzzles', 'Teams', 'Halloween', 'Mystery'],
      vendors: ['5', '10', '14'],
      theme: 'Escape',
      enableRSVP: true,
      enableBudgetTracker: true,
      enableTodoChecklist: true,
      createdAt: DateTime(2024, 5, 7),
    ),
    
    Event(
      id: '8',
      name: 'Art & Culture Night',
      title: 'Art & Culture Night',
      description: 'An evening celebrating local artists, performers, and cultural exhibitions.',
      imageUrl: 'assets/art_night.png',
      date: DateTime(2024, 7, 27),
      time: '6:00 PM - 11:00 PM',
      location: 'Downtown Gallery',
      category: 'Arts',
      price: 10.0,
      attendees: ['350'],
      tags: ['Art', 'Culture', 'Exhibition'],
      vendors: ['4', '9'],
      theme: 'Culture',
      enableRSVP: true,
      enableBudgetTracker: false,
      enableTodoChecklist: true,
      createdAt: DateTime(2024, 5, 8),
    ),
    
    Event(
      id: '9',
      name: 'Ballroom Dance Soiree',
      title: 'Ballroom Dance Soiree',
      description: 'Elegant evening of ballroom dancing with live orchestra and professional demonstrations.',
      imageUrl: 'assets/dance.png',
      date: DateTime(2024, 6, 30),
      time: '7:00 PM - 11:00 PM',
      location: 'The Grand Hall',
      category: 'Dance',
      price: 40.0,
      attendees: ['150'],
      tags: ['Dance', 'Ballroom', 'Formal'],
      vendors: ['6'],
      theme: 'Ballroom',
      enableRSVP: true,
      enableBudgetTracker: false,
      enableTodoChecklist: true,
      createdAt: DateTime(2024, 5, 9),
    ),
    
    Event(
      id: '10',
      name: 'Gourmet Food Festival',
      title: 'Gourmet Food Festival',
      description: 'Sample culinary delights from top chefs and food vendors from around the region.',
      imageUrl: 'assets/food_festival.png',
      date: DateTime(2024, 8, 4),
      time: '11:00 AM - 8:00 PM',
      location: 'Market Square',
      category: 'Food',
      price: 25.0,
      attendees: ['1200'],
      tags: ['Food', 'Culinary', 'Tasting'],
      vendors: ['3', '5', '10'],
      theme: 'Food',
      enableRSVP: true,
      enableBudgetTracker: true,
      enableTodoChecklist: true,
      createdAt: DateTime(2024, 5, 10),
    ),
    
    Event(
      id: '13',
      name: 'Vineyard Wine Tasting',
      title: 'Vineyard Wine Tasting',
      description: 'Sample premium wines from local vineyards with cheese pairings and vineyard tours.',
      imageUrl: 'assets/wine_tasting.png',
      date: DateTime(2024, 7, 7),
      time: '1:00 PM - 5:00 PM',
      location: 'Green Valley',
      category: 'Food & Drink',
      price: 45.0,
      attendees: ['120'],
      tags: ['Wine', 'Tasting', 'Tour'],
      vendors: ['5'],
      theme: 'Wine',
      enableRSVP: true,
      enableBudgetTracker: true,
      enableTodoChecklist: true,
      createdAt: DateTime(2024, 5, 13),
    ),
  ];

  // Sample User Profile
  static UserProfile currentUser = UserProfile(
    id: 'user1',
    name: 'Riya',
    imageUrl: 'assets/images/user_profile.jpg',
    role: 'Event Planner',
    eventsPlanned: 23,
    eventsAttended: 45,
    followers: 120,
    myEvents: [
      Event(
        id: '101',
        name: 'Luxury Wedding Showcase',
        title: 'Luxury Wedding Showcase',
        description: 'Exclusive wedding fair featuring luxury vendors and services.',
        imageUrl: 'assets/wedding_show.png',
        date: DateTime(2024, 8, 12),
        time: '11:00 AM - 6:00 PM',
        location: 'Grace Grand Hotel',
        category: 'Wedding',
        theme: 'Luxury',
        enableRSVP: true,
        enableBudgetTracker: true,
        enableTodoChecklist: true,
        createdAt: DateTime(2024, 6, 1),
      ),
      Event(
        id: '102',
        name: 'Corporate Wellness Retreat',
        title: 'Corporate Wellness Retreat',
        description: 'Team-building and wellness activities for corporate groups.',
        imageUrl: 'assets/images/corporate_retreat.jpg',
        date: DateTime(2024, 9, 3),
        time: 'All Day',
        location: 'Mountain Springs Resort',
        category: 'Corporate',
        theme: 'Wellness',
        enableRSVP: true,
        enableBudgetTracker: true,
        enableTodoChecklist: true,
        createdAt: DateTime(2024, 6, 2),
      ),
      Event(
        id: '103',
        name: 'Annual Charity Gala',
        title: 'Annual Charity Gala',
        description: 'Black-tie fundraising event supporting local children\'s hospital.',
        imageUrl: 'assets/images/charity_gala.jpg',
        date: DateTime(2024, 10, 15),
        time: '7:00 PM - 11:00 PM',
        location: 'The Ritz Ballroom',
        category: 'Charity',
        theme: 'Charity',
        enableRSVP: true,
        enableBudgetTracker: true,
        enableTodoChecklist: true,
        createdAt: DateTime(2024, 6, 3),
      ),
    ],
    savedThemes: [
      'Rustic Wedding',
      'Modern Minimalist',
      'Garden Party',
      'Vintage Glam',
    ],
    wishlist: [],
  );

  // Enhanced Sample Vendors with complete information
  static List<Vendor> vendors = [
    Vendor(
      id: '1',
      name: 'Floral Elegance',
      imageUrl: 'assets/floral_elegance.png',
      category: 'Florist',
      rating: 4.8,
      description: 'Premium floral designs for weddings and special events. We specialize in custom bouquets, centerpieces, and full venue decorations using the freshest flowers sourced from local and international growers.',
      location: 'Downtown',
      priceRange: '\$200 - \$2,000',
      contact: '+1 (555) 123-4567',
      email: 'info@floralelegance.com',
      tags: ['Wedding', 'Bouquets', 'Centerpieces', 'Event Decor', 'Custom Arrangements'],
      images: [
        'assets/floral elegance.png.jpg',
        'assets/floral1.jpg',
        'assets/floral2.jpg',
        'assets/floral3.jpg',
      ],
      isFeatured: true,
    ),
    Vendor(
      id: '3',
      name: 'Gourmet Catering',
      imageUrl: 'assets/catering.png',
      category: 'Catering',
      rating: 4.7,
      description: 'Full-service catering for events of all sizes. From intimate gatherings to large corporate events, we provide exceptional cuisine and professional service that exceeds expectations.',
      location: 'Citywide',
      priceRange: '\$25 - \$150 per person',
      contact: '+1 (555) 345-6789',
      email: 'catering@gourmetcatering.com',
      tags: ['Buffet', 'Plated Service', 'Cocktail Catering', 'Corporate Events', 'Dietary Accommodations'],
      images: [
        'assets/catering.png.jpg',
        'assets/cater1.jpg',
        'assets/cater2.jpg',
        'assets/cater3.jpg',
      ],
      isFeatured: false,
    ),
    Vendor(
      id: '4',
      name: 'Dream Decor',
      imageUrl: 'assets/decor.png',
      category: 'Decor',
      rating: 4.6,
      description: 'Event decorations, rentals, and styling services. We transform spaces into magical environments with our extensive inventory of linens, lighting, furniture, and decorative elements.',
      location: 'Central',
      priceRange: '\$300 - \$5,000',
      contact: '+1 (555) 456-7890',
      email: 'design@dreamdecor.com',
      tags: ['Lighting', 'Furniture Rental', 'Props', 'Linens', 'Backdrop Design'],
      images: [
        'assets/place1.jpg',
        'assets/place2.jpg',
        'assets/place3.jpg',
        'assets/vendor decor.png.jpg',
      ],
      isFeatured: false,
    ),
    Vendor(
      id: '5',
      name: 'Melody Masters',
      imageUrl: 'assets/music_band.png',
      category: 'Entertainment',
      rating: 4.9,
      description: 'Professional live bands and DJs for weddings, parties, and corporate events. Our talented musicians and DJs create the perfect atmosphere for your special occasion with customized playlists and professional sound systems.',
      location: 'Downtown',
      priceRange: '\$500 - \$3,000',
      contact: '+1 (555) 567-8901',
      email: 'bookings@melodymasters.com',
      tags: ['Live Music', 'DJ Services', 'Sound System', 'Wedding Music', 'Corporate Entertainment'],
      images: [
        'assets/band1.png',
        'assets/band2.png',
        'assets/band3.png',
        'assets/band4.png',
      ],
      isFeatured: true,
    ),
    Vendor(
      id: '7',
      name: 'Elite Transportation',
      imageUrl: 'assets/transportation.png',
      category: 'Transportation',
      rating: 4.7,
      description: 'Luxury transportation services including limousines, party buses, and vintage cars. Arrive in style with our premium fleet and professional chauffeurs who ensure a safe and elegant journey.',
      location: 'Metropolitan Area',
      priceRange: '\$200 - \$1,200',
      contact: '+1 (555) 789-0123',
      email: 'reservations@elitetransport.com',
      tags: ['Limousines', 'Party Bus', 'Wedding Cars', 'Airport Transfers', 'Corporate Transportation'],
      images: [
        'assets/trans1.png',
        'assets/trans2.png',
        'assets/trans3.png',
        'assets/trans4.png',
      ],
      isFeatured: false,
    ),
    Vendor(
      id: '10',
      name: 'Bartender Express',
      imageUrl: 'assets/bartender.png',
      category: 'Bar Services',
      rating: 4.6,
      description: 'Professional bartending services with premium cocktails and mobile bar setups. Our skilled mixologists create signature drinks and provide full bar service for your event.',
      location: 'Citywide',
      priceRange: '\$300 - \$2,000',
      contact: '+1 (555) 012-3456',
      email: 'bookings@bartenderexpress.com',
      tags: ['Mobile Bar', 'Cocktail Service', 'Wine Service', 'Signature Drinks', 'Bar Equipment Rental'],
      images: [
        'assets/bar1.jpg',
        'assets/bar2.jpg',
        'assets/bar3.jpg',
        'assets/bar4.jpg',
      ],
      isFeatured: false,
    ),
    Vendor(
      id: '13',
      name: 'Lighting Specialists',
      imageUrl: 'assets/lighting.png',
      category: 'Lighting',
      rating: 4.8,
      description: 'Professional event lighting including uplighting, string lights, and dance floor lighting. We create ambiance and atmosphere with our state-of-the-art lighting equipment and design expertise.',
      location: 'Central',
      priceRange: '\$250 - \$3,000',
      contact: '+1 (555) 345-9012',
      email: 'illuminate@lightingspec.com',
      tags: ['Uplighting', 'String Lights', 'Dance Floor Lighting', 'Gobos', 'LED Effects'],
      images: [
        'assets/lights1.png',
        'assets/lights2.png',
        'assets/lights3.png',
        'assets/lights4.png',
      ],
      isFeatured: true,
    ),
  ];

  // Event Timeline Tasks
  static List<Map<String, dynamic>> eventTimelineTasks = [
    {
      'title': 'Venue Selection Confirmed',
      'date': 'Feb 15',
      'completed': true,
    },
    {
      'title': 'Invitations Sent',
      'date': 'Mar 1',
      'completed': true,
    },
    {
      'title': 'Vendors Finalized',
      'date': 'Mar 15',
      'completed': false,
    },
    {
      'title': 'Food Order RSVP Due',
      'date': 'Apr 1',
      'completed': false,
    },
  ];
}