import '../event.dart';
import '../user_profile.dart';
import '../vendor.dart';

class MockData {
  // Sample Events
  static List<Event> sampleEvents = [
    Event(
      id: '1',
      name: 'Summer Festival 2024', // Added required name parameter
      title: 'Summer Festival 2024',
      description: 'Join us for a weekend of music, art, and fun at the annual Summer Festival.',
      imageUrl: 'assets/summer_party.png',
      date: 'Jun 15-16',
      time: '10:00 AM - 10:00 PM',
      location: 'City Park',
      category: 'Festival',
      price: 25.0,
      attendees: ['2500'],
      tags: ['Music', 'Art', 'Food', 'Family-friendly'],
      vendors: ['3', '5', '7'],
      theme: 'Summer',
      enableRSVP: true,
      enableBudgetTracker: true,
      enableTodoChecklist: true,
      createdAt: DateTime(2024, 5, 1),
    ),
    
    Event(
      id: '2',
      name: 'Elegant Wedding Show', // Added required name parameter
      title: 'Elegant Wedding Show',
      description: 'Discover the latest wedding trends, meet vendors, and get inspired for your big day.',
      imageUrl: 'assets/wedding_show.png',
      date: 'Jul 21',
      time: '12:00 PM - 5:00 PM',
      location: 'Grand Hotel',
      category: 'Expo',
      price: 15.0,
      attendees: ['800'],
      tags: ['Wedding', 'Bridal', 'Fashion'],
      vendors: ['1', '2', '8'],
      theme: 'Wedding',
      enableRSVP: true,
      enableBudgetTracker: true,
      enableTodoChecklist: true,
      createdAt: DateTime(2024, 5, 2),
    ),
    
    Event(
      id: '3',
      name: 'Retro Game Night Extravaganza', // Added required name parameter
      title: 'Retro Game Night Extravaganza',
      description: 'Step back in time with classic arcade games, board games, and retro video games. Prizes, snacks, and nostalgic fun for all ages!',
      imageUrl: 'assets/retro_gaming.png',
      date: 'Jul 12',
      time: '6:00 PM - 11:00 PM',
      location: 'Gaming Lounge Downtown',
      category: 'Entertainment',
      price: 20.0,
      attendees: ['150'],
      tags: ['Gaming', 'Retro', 'Fun'],
      vendors: ['2', '8', '15'],
      theme: 'Retro',
      enableRSVP: true,
      enableBudgetTracker: false,
      enableTodoChecklist: true,
      createdAt: DateTime(2024, 5, 3),
    ),

    Event(
      id: '4',
      name: 'Glow-in-the-Dark Mini Golf Tournament', // Added required name parameter
      title: 'Glow-in-the-Dark Mini Golf Tournament',
      description: 'Experience mini golf like never before! Neon lights, glowing obstacles, and cosmic fun. Tournament prizes and glow party afterwards!',
      imageUrl: 'assets/glow_golf.png',
      date: 'Aug 18',
      time: '7:00 PM - 10:30 PM',
      location: 'Cosmic Golf Adventure',
      category: 'Sports',
      price: 15.0,
      attendees: ['200'],
      tags: ['Mini Golf', 'Glow', 'Tournament'],
      vendors: ['4', '9', '12'],
      theme: 'Glow',
      enableRSVP: true,
      enableBudgetTracker: false,
      enableTodoChecklist: true,
      createdAt: DateTime(2024, 5, 4),
    ),

    Event(
      id: '5',
      name: 'Paint & Sip Comedy Night', // Added required name parameter
      title: 'Paint & Sip Comedy Night',
      description: 'Create masterpieces while laughing at hilarious stand-up comedy! All art supplies included plus unlimited drinks and snacks.',
      imageUrl: 'assets/paint_comedy.png',
      date: 'Sep 7',
      time: '7:30 PM - 10:00 PM',
      location: 'Art Studio & Bar',
      category: 'Art',
      price: 35.0,
      attendees: ['80'],
      tags: ['Painting', 'Comedy', 'Drinks'],
      vendors: ['1', '6', '11'],
      theme: 'Art',
      enableRSVP: true,
      enableBudgetTracker: true,
      enableTodoChecklist: true,
      createdAt: DateTime(2024, 5, 5),
    ),

    Event(
      id: '6',
      name: 'Bubble Run Fun Challenge', // Added required name parameter
      title: 'Bubble Run Fun Challenge',
      description: 'Run through thousands of colorful bubbles in this 5K fun run! Not timed, just pure joy. Bubble machines, music, and celebration!',
      imageUrl: 'assets/bubble_run.png',
      date: 'May 25',
      time: '9:00 AM - 12:00 PM',
      location: 'Sunshine Park',
      category: 'Sports',
      price: 30.0,
      attendees: ['1000'],
      tags: ['Bubbles', 'Fun Run', 'Colorful'],
      vendors: ['3', '7', '13'],
      theme: 'Fun Run',
      enableRSVP: true,
      enableBudgetTracker: false,
      enableTodoChecklist: true,
      createdAt: DateTime(2024, 5, 6),
    ),
    
    Event(
      id: '7',
      name: 'Escape Room Championship', // Added required name parameter
      title: 'Escape Room Championship',
      description: 'Teams compete in multiple themed escape rooms! Zombie apocalypse, space station, haunted mansion, and more. Ultimate puzzle challenge!',
      imageUrl: 'assets/escape_rooms.png',
      date: 'Oct 31',
      time: '2:00 PM - 8:00 PM',
      location: 'Mystery Escape Complex',
      category: 'Entertainment',
      price: 40.0,
      attendees: ['120'],
      tags: ['Escape Room', 'Puzzles', 'Teams', 'Halloween', 'Mystery'],
      vendors: ['5', '10', '14'],
      theme: 'Escape',
      enableRSVP: true,
      enableBudgetTracker: true,
      enableTodoChecklist: true,
      createdAt: DateTime(2024, 5, 7),
    ),
    
    Event(
      id: '8',
      name: 'Art & Culture Night', // Added required name parameter
      title: 'Art & Culture Night',
      description: 'An evening celebrating local artists, performers, and cultural exhibitions.',
      imageUrl: 'assets/art_night.png',
      date: 'Jul 27',
      time: '6:00 PM - 11:00 PM',
      location: 'Downtown Gallery',
      category: 'Arts',
      price: 10.0,
      attendees: ['350'],
      tags: ['Art', 'Culture', 'Exhibition'],
      vendors: ['4', '9'],
      theme: 'Culture',
      enableRSVP: true,
      enableBudgetTracker: false,
      enableTodoChecklist: true,
      createdAt: DateTime(2024, 5, 8),
    ),
    
    Event(
      id: '9',
      name: 'Ballroom Dance Soiree', // Added required name parameter
      title: 'Ballroom Dance Soiree',
      description: 'Elegant evening of ballroom dancing with live orchestra and professional demonstrations.',
      imageUrl: 'assets/dance.png',
      date: 'Jun 30',
      time: '7:00 PM - 11:00 PM',
      location: 'The Grand Hall',
      category: 'Dance',
      price: 40.0,
      attendees: ['150'],
      tags: ['Dance', 'Ballroom', 'Formal'],
      vendors: ['6'],
      theme: 'Ballroom',
      enableRSVP: true,
      enableBudgetTracker: false,
      enableTodoChecklist: true,
      createdAt: DateTime(2024, 5, 9),
    ),
    
    Event(
      id: '10',
      name: 'Gourmet Food Festival', // Added required name parameter
      title: 'Gourmet Food Festival',
      description: 'Sample culinary delights from top chefs and food vendors from around the region.',
      imageUrl: 'assets/food_festival.png',
      date: 'Aug 4-7',
      time: '11:00 AM - 8:00 PM',
      location: 'Market Square',
      category: 'Food',
      price: 25.0,
      attendees: ['1200'],
      tags: ['Food', 'Culinary', 'Tasting'],
      vendors: ['3', '5', '10'],
      theme: 'Food',
      enableRSVP: true,
      enableBudgetTracker: true,
      enableTodoChecklist: true,
      createdAt: DateTime(2024, 5, 10),
    ),
    
    Event(
      id: '13',
      name: 'Vineyard Wine Tasting', // Added required name parameter
      title: 'Vineyard Wine Tasting',
      description: 'Sample premium wines from local vineyards with cheese pairings and vineyard tours.',
      imageUrl: 'assets/wine_tasting.png',
      date: 'Jul 7',
      time: '1:00 PM - 5:00 PM',
      location: 'Green Valley',
      category: 'Food & Drink',
      price: 45.0,
      attendees: ['120'],
      tags: ['Wine', 'Tasting', 'Tour'],
      vendors: ['5'],
      theme: 'Wine',
      enableRSVP: true,
      enableBudgetTracker: true,
      enableTodoChecklist: true,
      createdAt: DateTime(2024, 5, 13),
    ),
  ];

  // Sample User Profile
  static UserProfile currentUser = UserProfile(
    id: 'user1',
    name: 'Riya',
    imageUrl: 'assets/images/user_profile.jpg',
    role: 'Event Planner',
    eventsPlanned: 23,
    eventsAttended: 45,
    followers: 120,
    myEvents: [
      Event(
        id: '101',
        name: 'Luxury Wedding Showcase', // Added required name parameter
        title: 'Luxury Wedding Showcase',
        description: 'Exclusive wedding fair featuring luxury vendors and services.',
        imageUrl: 'assets/wedding_show.png',
        date: 'Aug 12',
        time: '11:00 AM - 6:00 PM',
        location: 'Grace Grand Hotel',
        category: 'Wedding',
        theme: 'Luxury',
        enableRSVP: true,
        enableBudgetTracker: true,
        enableTodoChecklist: true,
        createdAt: DateTime(2024, 6, 1),
      ),
      Event(
        id: '102',
        name: 'Corporate Wellness Retreat', // Added required name parameter
        title: 'Corporate Wellness Retreat',
        description: 'Team-building and wellness activities for corporate groups.',
        imageUrl: 'assets/images/corporate_retreat.jpg',
        date: 'Sep 3-5',
        time: 'All Day',
        location: 'Mountain Springs Resort',
        category: 'Corporate',
        theme: 'Wellness',
        enableRSVP: true,
        enableBudgetTracker: true,
        enableTodoChecklist: true,
        createdAt: DateTime(2024, 6, 2),
      ),
      Event(
        id: '103',
        name: 'Annual Charity Gala', // Added required name parameter
        title: 'Annual Charity Gala',
        description: 'Black-tie fundraising event supporting local children\'s hospital.',
        imageUrl: 'assets/images/charity_gala.jpg',
        date: 'Oct 15',
        time: '7:00 PM - 11:00 PM',
        location: 'The Ritz Ballroom',
        category: 'Charity',
        theme: 'Charity',
        enableRSVP: true,
        enableBudgetTracker: true,
        enableTodoChecklist: true,
        createdAt: DateTime(2024, 6, 3),
      ),
    ],
    savedThemes: [
      'Rustic Wedding',
      'Modern Minimalist',
      'Garden Party',
      'Vintage Glam',
    ],
    wishlist: [], // Added required wishlist parameter
  );

  // Sample Vendors
  static List<Vendor> vendors = [
    Vendor(
      id: '1',
      name: 'Floral Elegance',
      imageUrl: 'assets/floral elegance.png.jpg',
      category: 'Florist',
      rating: 4.8,
      description: 'Premium floral designs for weddings and special events.',
      location: 'Downtown',
      tags: ['Wedding', 'Bouquets', 'Centerpieces'],
      images: [
        'assets/images/floral1.jpg',
        'assets/images/floral2.jpg',
        'assets/images/floral3.jpg',
      ],
      isFeatured: true,
    ),
    Vendor(
      id: '2',
      name: 'Cake Couture',
      imageUrl: 'assets/cake.png.jpg',
      category: 'Catering',
      rating: 4.9,
      description: 'Custom cakes and desserts for weddings and special occasions.',
      location: 'Westside',
      tags: ['Wedding Cakes', 'Desserts', 'Custom Designs'],
      images: [
        'assets/images/cake1.jpg',
        'assets/images/cake2.jpg',
        'assets/images/cake3.jpg',
      ],
      isFeatured: true,
    ),
    Vendor(
      id: '3',
      name: 'Gourmet Catering',
      imageUrl: 'assets/catering.png.jpg',
      category: 'Catering',
      rating: 4.7,
      description: 'Full-service catering for events of all sizes.',
      location: 'Citywide',
      tags: ['Buffet', 'Plated', 'Cocktail'],
      images: [
        'assets/images/catering1.jpg',
        'assets/images/catering2.jpg',
        'assets/images/catering3.jpg',
      ],
      isFeatured: false,
    ),
    Vendor(
      id: '4',
      name: 'Decor',
      imageUrl: 'assets/decor.png.jpg',
      category: 'Decor',
      rating: 4.6,
      description: 'Event decorations, rentals, and styling services.',
      location: 'Central',
      tags: ['Lighting', 'Furniture', 'Props'],
      images: [
        'assets/images/decor1.jpg',
        'assets/images/decor2.jpg',
        'assets/images/decor3.jpg',
      ],
      isFeatured: false,
    ),
    Vendor(
      id: '5',
      name: 'Melody Masters',
      imageUrl: 'assets/music_band.png.jpg',
      category: 'Entertainment',
      rating: 4.9,
      description: 'Professional live bands and DJs for weddings, parties, and corporate events.',
      location: 'Downtown',
      tags: ['Live Music', 'DJ Services', 'Sound System'],
      images: [
        'assets/images/band1.jpg',
        'assets/images/band2.jpg',
        'assets/images/band3.jpg',
      ],
      isFeatured: true,
    ),
    Vendor(
      id: '7',
      name: 'Elite Transportation',
      imageUrl: 'assets/transportation.png.jpg',
      category: 'Transportation',
      rating: 4.7,
      description: 'Luxury transportation services including limousines, party buses, and vintage cars.',
      location: 'Metropolitan Area',
      tags: ['Limousines', 'Party Bus', 'Wedding Cars'],
      images: [
        'assets/images/limo1.jpg',
        'assets/images/limo2.jpg',
        'assets/images/limo3.jpg',
      ],
      isFeatured: false,
    ),
    Vendor(
      id: '10',
      name: 'Bartender Express',
      imageUrl: 'assets/bartender.png.jpg',
      category: 'Bar Services',
      rating: 4.6,
      description: 'Professional bartending services with premium cocktails and mobile bar setups.',
      location: 'Citywide',
      tags: ['Mobile Bar', 'Cocktail Service', 'Wine Service'],
      images: [
        'assets/images/bar1.jpg',
        'assets/images/bar2.jpg',
        'assets/images/bar3.jpg',
      ],
      isFeatured: false,
    ),
    Vendor(
      id: '13',
      name: 'Lighting Specialists',
      imageUrl: 'assets/lighting.png.jpg',
      category: 'Lighting',
      rating: 4.8,
      description: 'Professional event lighting including uplighting, string lights, and dance floor lighting.',
      location: 'Central',
      tags: ['Uplighting', 'String Lights', 'Dance Floor Lighting'],
      images: [
        'assets/images/lighting1.jpg',
        'assets/images/lighting2.jpg',
        'assets/images/lighting3.jpg',
      ],
      isFeatured: true,
    ),
  ];

  // Event Timeline Tasks
  static List<Map<String, dynamic>> eventTimelineTasks = [
    {
      'title': 'Venue Selection Confirmed',
      'date': 'Feb 15',
      'completed': true,
    },
    {
      'title': 'Invitations Sent',
      'date': 'Mar 1',
      'completed': true,
    },
    {
      'title': 'Vendors Finalized',
      'date': 'Mar 15',
      'completed': false,
    },
    {
      'title': 'Food Order RSVP Due',
      'date': 'Apr 1',
      'completed': false,
    },
  ];
}